FROM centos:latest
MAINTAINER linyows <linyows@gmail.com>

RUN yum install -y glibc gcc make libcurl-devel jansson-devel bzip2 unzip rpmdevtools mock

RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
RUN sed -i "s;%_build_name_fmt.*;%_build_name_fmt\t%%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.el7.%%{ARCH}.rpm;" /usr/lib/rpm/macros

RUN mkdir /octopass
WORKDIR /octopass
