FROM ubuntu:focal
MAINTAINER linyows <linyows@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -qq update && \
    apt-get install -qq glibc-source gcc make libcurl4-gnutls-dev libjansson-dev \
                        bzip2 unzip debhelper dh-make devscripts cdbs clang

ENV USER root

RUN mkdir /octopass
WORKDIR /octopass
