ARG BASE_IMAGE=rockylinux:9
FROM ${BASE_IMAGE}

RUN dnf install -y \
    rpm-build \
    make \
    selinux-policy-devel \
    binutils \
    && dnf clean all

# Copy pre-built binaries and config example
COPY zig-out/ /zig-out/
COPY packaging/octopass.conf.example /

WORKDIR /packaging

ENTRYPOINT ["sh", "-c", "make -f Makefile.container info && make -f Makefile.container rpm_pkg && make -f Makefile.container test_rpm"]
