FROM centos:latest
MAINTAINER linyows <linyows@gmail.com>

RUN yum install -y gcc make curl-devel jansson-devel nss-devel\
                   autoconf libtool wget bzip2 git vim

RUN mkdir /octopass
WORKDIR /octopass
