# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'linyows/centos-7.2_chef-12.12_puppet-4.5'
  config.vm.network :private_network, ip: '192.168.10.10'
  config.vm.synced_folder '.', '/octopass'

  config.vm.provision 'shell', inline: <<-SHELL
    yum install -y gcc make curl-devel jansson-devel nss-devel autoconf libtool git vim
    git clone --depth=1 https://github.com/vstakhov/libucl.git && \
      pushd libucl && ./autogen.sh && ./configure && make && make install && popd
    git clone https://github.com/allanjude/uclcmd.git
  SHELL
end
